# Created by MichaelCurrin
# https://gist.github.com/MichaelCurrin/a698731096f78240f653faf9a9127cba

name: Build and move to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@master
        with:
          persist-credentials: false
          submodules: true # TODO remove this if not using submodules in Hexo

      - name: Install ğŸ”§
        run: |
          cd css-product
          npm install

      - name: Build ğŸ—ï¸
        run: |
          cd css-product
          npm run build
      - name: Deploy to GH Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN_CSS }}
          publish_dir: css-product/dist

          # github_token credential don't have enough access to create gh-pages branch
          # So to resolve that, create a PAT with access to specific repo's branch creation
          # permission
